### PR TITLE
Already voted closure

### PR DESCRIPTION
**Pull request by JamesSedlacek**
I'm thinking we could have 1 closure like this that can handle all error states?
Error state cases like: loadingFailure & alreadyVoted

### CODE REVIEW

**Review by AvdLee — CHANGES_REQUESTED** [review]
It's more a design decision, but I rather see us remove the vote instead of showing the alert. If a user accidentally voted, he could revert that decision.

[We can use the CountAPI to lower the number of votes:](https://countapi.xyz/)
CleanShot 2023-02-22 at 11 57 44@2x

**Comment by jordibruin** [comment]
@AvdLee I'm a bit worried to use that endpoint, because if for some reason the value has not been loaded properly it will be set to 0, and then a user could accidentally reset the entire vote count for a feature.

**Comment by AvdLee** [comment]
> because if for some reason the value has not been loaded properly

You've contacted the Count API owner before, right? Can we ask him for a decrement API endpoint?

**Comment by Sherlouk** [comment]
> if for some reason the value has not been loaded properly it will be set to 0

Could you expand on your understanding here please @jordibruin? 

Looking at the API, it doesn't set the count but rather increments it by a given value (so -1 would simply reduce the count by 1 on the server - irrespective of the local store). 

The only way this would set to 0 is if the user was able to remove their vote multiple times without adding a vote (and did this many times), which should be impossible with the current pattern where we wait for a successful vote claim before updating the 'alreadyVoted' state.

**Comment by AvdLee** [comment]
> Looking at the API, it doesn't set the count but rather increments it by a given value (so -1 would simply reduce the count by 1 on the server - irrespective of the local store).

You're completely right! We should indeed be able to implement this using that API endpoint 🙏

**Comment by AvdLee** [comment]
Closing this PR since we implemented removing votes

**Pull request closed without merging**
