### PR TITLE
Adds support for iOS 15.

### PR DESCRIPTION
**Pull request by anmolmalhotra**
This was super easy to support. :) This will add support for iOS 15 (#48). I am also attaching screenshot of app running on iOS 15.

App running on iOS 15 Simulator

### CODE REVIEW

**Review by AvdLee — APPROVED** [review]
Nice, love it!

**Comment by jordibruin** [comment]
This broke stuff 🙂  fixing now. Let's be a bit more thorough in the future with merging these things. 
image

Also, supporting 15 like this will lead to more work for major new features in the future so I would have suggested we waited a bit before doing this 🙃

**Comment by jordibruin** [comment]
Just want to clarify, the reason it broke stuff was because new things got added in another PR. Thanks for starting us on the road to iOS 15 support @anmolmalhotra ❤️‍🔥

**Comment by anmolmalhotra** [comment]
@jordibruin oh nooo! I hope there are workarounds for these errors. Happy to pitch in to fix these if you want. ☺️

**Pull request merged**
